language: rust
cache: cargo
rust:
  - 1.26.0
addons:
  apt:
    update: true

matrix:
  include:
  - os: linux
    env: TARGET=x86_64-unknown-linux-gnu
    before_install:
      - sudo apt-get install -y libusb-1.0-0-dev
  - os: osx
    env: TARGET=x86_64-apple-darwin
env:
  global:
    - PROJECT_NAME=sync-dir

before_deploy:
  - make
  - tar czf "$(pwd)/$PROJECT_NAME-$TRAVIS_TAG-$TARGET.tar.gz" bin/*

deploy:
  provider: releases
  api_key:
    secure: "Y6KEkSJuqPESyn14M5kOpQO6JG1Lu2QSTMPQmyBeJB6TOYkq/BmblKoOTEgCAcB62UIDpOF2ErsZe/eCjTPjpPvszL+Sup/ql4odRxwua4KF5AFbeNQgdWhULsTkFd/AqWkcJMfSe0nze6CKsWPOdYx5u9C2NnfivL+qHNxr/KpLUB9bwDZHc8NkioO081C9N76JiPpCGwgHQEOmmtM7t0W2J/AyojNVOQpg9dINFZxlRze7bUA5B/oX+spTJtaWeIx0eCgr5ETsRhu6CRX6KIdShmvQvHZXMObGciCeHu0vif+wMMwbqTn5kcWaPzJvqsQMD2cV45wPy7YLWKX+VQf6YPSBOs1+y20KFEdYkTJm3A47CTWz7XCWqKW58ZhHL3vLbl9M/ukkNI7iNqbK+Il1lGNYX/y8bjj9MfBs1GxSZaLRL5oGOYnoocvcET7uU7CxD9wHQScOuDTTR19lMxS0H1WHlxt1WYLItLro16d/qYhcmYwC/f+8FgPcFoBh9r4f2lkGM44rYU9qvq66vRPHT/gc1/1jfpwBsTU3tYBcW/p28JWy9y6nLeT0lWr9NgmUd138xCet9fPZZZq26IpoeVSMYnR28r4CvcaTYKndlUCC1XXLWmvrQDMIHY0/VXIbsizcNEWvKTc0ZvDlt5CKav+GcOSknY+zLz1e96k="
  skip_cleanup: true
  file_glob: true
  file:
    - $PROJECT_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    tags: true
notifications:
  email:
    on_success: change
    on_failure: change
