version: 2
jobs:
  build:
    docker:
      - image: 'rust:1.25.0'
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - >-
              cache-key-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum
              "Cargo.lock" }}
      - save_cache:
          name: Save cache
          paths:
            - ~/.cargo
            - ~/app/target
          key: >-
            cache-key-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum
            "Cargo.lock" }}
      - run:
          name: Update toolchain
          command: rustup update
      - run:
          name: Run tests
          command: cargo test
